### ISSUE TITLE
SDK Merge & Final Cleanup

### ISSUE THREAD

**Issue by ehotinger** [AppPlatPerf/azure-cli#228]
- [x] https://github.com/AzureCR/azure-cli/issues/211 (update SDK)
- [x] In `build.py`, make sure we clean up the client creation:

```
# TODO: Remove this import once the SDK is merged.
    from ._client_factory import cf_acr_registries_build
    client_registries = cf_acr_registries_build(cmd.cli_ctx)
```

- [x] In `run.py`, clean up the client creation.
- [x] In the `_run_polling.py`, clean up the SDK models reference.
